"use client";
import { useRef, useEffect, useState } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RewardOverlay from "./_components/rewardOverlay";
import { usePathname } from "next/navigation";
import { FocusCyberAudio } from "./soundEngine/ciberFocus";
import { CyberArcadeAudio } from "./soundEngine/ciberPunkAudio";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Mapa de rutas a archivos de audio
const audioMap = {
  "/": "/audio/albin myers - elektro punk.mp3",
  "/shapesGame": "/audio/FJ Project - Electro Punk.mp3",
  "/visualMath": "/audio/albin myers - elektro punk.mp3",
  // puedes añadir más rutas
};

export default function RootLayout({ children }) {
  const audioRef = useRef(null);
  const [userInteracted, setUserInteracted] = useState(false);
  const pathname = usePathname();

  const cyberAudioRef = useRef(null); // para la instancia de FocusCyberAudio

  // Determinar qué audio debe sonar según la ruta
  const isCyberRoute = pathname === "/shapesGame"; // cambia esto a tu ruta deseada

  // Efecto para manejar la interacción del usuario (click)
  useEffect(() => {
    const handleUserInteraction = () => {
      setUserInteracted(true);
      window.removeEventListener("click", handleUserInteraction);
    };
    window.addEventListener("click", handleUserInteraction);
    return () => window.removeEventListener("click", handleUserInteraction);
  }, []);

  // Efecto para controlar el audio según la ruta y la interacción
  useEffect(() => {
    if (!userInteracted) return; // esperar a que el usuario haga click

    if (isCyberRoute) {
      // Ruta cyber: usar FocusCyberAudio
      if (!cyberAudioRef.current) {
        cyberAudioRef.current = new CyberArcadeAudio();
        // Reanudar el AudioContext si está suspendido (requiere interacción)
        if (cyberAudioRef.current.ctx.state === "suspended") {
          cyberAudioRef.current.ctx.resume();
        }
        cyberAudioRef.current.start();
      }
      // Si había un MP3 sonando, lo detenemos
      if (audioRef.current) {
        audioRef.current.pause();
        audioRef.current.currentTime = 0;
      }
    } else {
      // Ruta normal: usar MP3
      if (cyberAudioRef.current) {
        cyberAudioRef.current.stop();
        cyberAudioRef.current = null;
      }
      if (audioRef.current) {
        audioRef.current.volume = 0.5;
        audioRef.current.play().catch(() => {});
      }
    }

    // Limpieza al desmontar el componente o cambiar de ruta
    return () => {
      if (cyberAudioRef.current) {
        cyberAudioRef.current.stop();
        cyberAudioRef.current = null;
      }
    };
  }, [isCyberRoute, userInteracted]);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <audio ref={audioRef} loop preload="auto" />

        {children}
        <RewardOverlay />
      </body>
    </html>
  );
}
