"use client";
import { useRef, useEffect, useState } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RewardOverlay from "./_components/rewardOverlay";
import { usePathname } from "next/navigation";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Mapa de rutas a archivos de audio
const audioMap = {
  "/": "/audio/albin myers - elektro punk.mp3",
  "/shapesGame": "/audio/FJ Project - Electro Punk.mp3",
  "/visualMath": "/audio/albin myers - elektro punk.mp3",
  // puedes añadir más rutas
};

export default function RootLayout({ children }) {
  const audioRef = useRef(null);
  const [isMuted, setIsMuted] = useState(false);
  const pathname = usePathname();

  // Inicializar audio al primer clic (como antes)
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;

    const startAudio = () => {
      audio.volume = 0.5;
      audio.play().catch(() => {});
      window.removeEventListener("click", startAudio);
    };
    window.addEventListener("click", startAudio);
    return () => window.removeEventListener("click", startAudio);
  }, []);

  // Cambiar la fuente cuando cambia la ruta
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;
    const src = audioMap[pathname] || audioMap["/"]; // fallback a la ruta raíz
    if (audio.src !== src) {
      audio.src = src;
      // Si ya está reproduciendo, seguir reproduciendo con la nueva fuente
      // (al cambiar src, se detiene automáticamente, así que podemos intentar reproducir)
      audio.load();
      if (!isMuted) {
        audio
          .play()
          .catch((e) =>
            console.log("Autoplay bloqueado, esperando interacción", e),
          );
      }
    }
  }, [pathname, isMuted]);

  const toggleMute = () => {
    if (audioRef.current) {
      audioRef.current.muted = !audioRef.current.muted;
      setIsMuted(!audioRef.current.muted);
    }
  };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <audio ref={audioRef} loop preload="auto" />
        <button
          onClick={toggleMute}
          style={{
            position: "fixed",
            bottom: 20,
            right: 20,
            zIndex: 1000,
            padding: "10px 15px",
            background: "#333",
            color: "#fff",
            border: "none",
            borderRadius: 5,
            cursor: "pointer",
          }}
        >
          {isMuted ? "🔇" : "🔊"}
        </button>
        {children}
        <RewardOverlay />
      </body>
    </html>
  );
}
